import type { EventBatchPayload } from '../app/taktApi'

export const heatEnergyDemoEventBatch: EventBatchPayload = {
  events: [
    {
      event_id: 'heat-demo-mkd-normal-poll-001',
      observed_at: '2026-05-19T06:12:30+00:00',
      protocol: 'MODBUS',
      operation: 'READ',
      asset_id: 'plc-itp-apartment-01',
      operator_id: 'operator-ivanov',
      payload_size: 192,
      source: 'plc_polling',
      payload: {
        scenario_id: 'moscow-apartment-boiler',
        facility_class: 'apartment_heat_point',
        route: 'dispatch_gateway_to_plc',
        service_desk_ref: 'SD-MSK-TE-5104',
        human_final_decision_required: true,
        no_active_control: true,
      },
    },
    {
      event_id: 'heat-demo-mkd-night-bypass-001',
      observed_at: '2026-05-12T23:17:44+00:00',
      protocol: 'MODBUS',
      operation: 'ADMIN_LOGIN',
      asset_id: 'plc-itp-apartment-01',
      operator_id: 'operator-ivanov',
      payload_size: 384,
      source: 'auth_logs',
      payload: {
        scenario_id: 'moscow-apartment-boiler',
        route: 'engineering_workstation_to_plc_without_jump_host',
        maintenance_window: false,
        manual_permit_present: false,
        human_final_decision_required: true,
        no_active_control: true,
      },
    },
    {
      event_id: 'heat-demo-hospital-night-login-001',
      observed_at: '2026-05-14T00:22:10+00:00',
      protocol: 'MODBUS',
      operation: 'ADMIN_LOGIN',
      asset_id: 'plc-hospital-boiler-01',
      operator_id: 'operator-petrova',
      payload_size: 416,
      source: 'auth_logs',
      payload: {
        scenario_id: 'moscow-hospital-boiler',
        facility_class: 'hospital_backup_boiler',
        maintenance_window: false,
        manual_permit_present: false,
        service_priority: 'critical',
        human_final_decision_required: true,
        no_active_control: true,
      },
    },
    {
      event_id: 'heat-demo-hospital-archive-stale-001',
      observed_at: '2026-05-13T22:48:35+00:00',
      protocol: 'OPC_UA',
      operation: 'READ',
      asset_id: 'archive-hospital-boiler-01',
      operator_id: 'operator-petrova',
      payload_size: 256,
      source: 'plc_polling',
      payload: {
        scenario_id: 'moscow-hospital-boiler',
        freshness_seconds: 5400,
        archive_lag_detected: true,
        human_final_decision_required: true,
        no_active_control: true,
      },
    },
    {
      event_id: 'heat-demo-industrial-shift-archive-001',
      observed_at: '2026-05-19T07:05:41+00:00',
      protocol: 'OPC_UA',
      operation: 'READ',
      asset_id: 'archive-industrial-shift-01',
      operator_id: 'operator-sidorov',
      payload_size: 224,
      source: 'service_desk',
      payload: {
        scenario_id: 'moscow-industrial-boiler',
        service_desk_ref: 'SD-MSK-TE-9102',
        maintenance_window: true,
        manual_permit_present: true,
        human_final_decision_required: true,
        no_active_control: true,
      },
    },
    {
      event_id: 'heat-demo-network-pressure-stale-001',
      observed_at: '2026-05-14T23:41:57+00:00',
      protocol: 'OPC_UA',
      operation: 'READ',
      asset_id: 'sensor-pressure-tk17',
      operator_id: 'operator-kuznetsova',
      payload_size: 208,
      source: 'plc_polling',
      payload: {
        scenario_id: 'moscow-heat-network',
        chamber: 'TK-17',
        freshness_seconds: 7200,
        dispatcher_cross_check_missing: true,
        human_final_decision_required: true,
        no_active_control: true,
      },
    },
    {
      event_id: 'heat-demo-ctp-normal-telemetry-001',
      observed_at: '2026-05-19T07:44:06+00:00',
      protocol: 'MODBUS',
      operation: 'READ',
      asset_id: 'cabinet-ctp-24',
      operator_id: 'operator-orlova',
      payload_size: 192,
      source: 'plc_polling',
      payload: {
        scenario_id: 'moscow-central-heat-point',
        route: 'dispatch_gateway_to_cabinet',
        service_desk_ref: 'SD-MSK-TE-7420',
        human_final_decision_required: true,
        no_active_control: true,
      },
    },
    {
      event_id: 'heat-demo-ctp-gvs-polling-unstable-001',
      observed_at: '2026-05-16T20:18:49+00:00',
      protocol: 'MODBUS',
      operation: 'READ',
      asset_id: 'plc-gvs-ctp-24',
      operator_id: 'operator-orlova',
      payload_size: 320,
      source: 'network_events',
      payload: {
        scenario_id: 'moscow-central-heat-point',
        polling_interval_jitter_seconds: 90,
        load_peak: true,
        manual_permit_present: false,
        human_final_decision_required: true,
        no_active_control: true,
      },
    },
  ],
}
