import type { DemoIncident, DemoLink, DemoNode, DemoScenario, DemoSegmentMode, DemoShiftPhase } from '../domain'

const allModes: DemoSegmentMode[] = ['NORMAL', 'DEGRADED', 'AIR-GAP', 'STORM']
const allPhases: DemoShiftPhase[] = ['WORK', 'NIGHT', 'MAINT']
const nightOnly: DemoShiftPhase[] = ['NIGHT']
const maintenanceOnly: DemoShiftPhase[] = ['MAINT']

export const demoScenarios: DemoScenario[] = [
  {
    id: 'moscow-apartment-boiler',
    title: 'Котельная многоэтажного дома',
    facility: 'ИТП жилого комплекса, Москва, район Хорошёво-Мнёвники',
    region: 'Москва',
    connectionPoint: 'Шкаф телемеханики ШТМ-1, контроллер теплового пункта',
    description: 'Контур отопления и ГВС жилого дома: погодозависимое регулирование, насосная группа, архив теплопотребления.',
    serviceContext: 'Ночная смена УК, регламентный доступ КИПиА только по заявке.',
  },
  {
    id: 'moscow-hospital-boiler',
    title: 'Котельная больницы',
    facility: 'Резервная котельная медицинского корпуса, Москва, район Сокольники',
    region: 'Москва',
    connectionPoint: 'Шкаф телемеханики ШТМ-Б, контроллер котла и насосов резерва',
    description: 'Критичный объект: контур отопления палат, резерв ГВС, аварийная вентиляция и архив параметров.',
    serviceContext: 'Повышенный приоритет, любые изменения требуют подтверждения дежурного инженера больницы.',
  },
  {
    id: 'moscow-industrial-boiler',
    title: 'Котельная предприятия',
    facility: 'Промышленная котельная производственного корпуса, Москва, район Печатники',
    region: 'Москва',
    connectionPoint: 'Шкаф телемеханики ШТМ-П, контроллер котлоагрегата и сетевых насосов',
    description: 'Нагрузка зависит от смены производства: паровой контур, сетевые насосы, шлюз АСУ ТП и архив сменных параметров.',
    serviceContext: 'Доступ через переходный сервер, плановые работы только в окно обслуживания.',
  },
  {
    id: 'moscow-heat-network',
    title: 'Тепловые сети',
    facility: 'Участок магистральной тепловой сети, Москва, район Нагатино-Садовники',
    region: 'Москва',
    connectionPoint: 'Шкаф телемеханики камеры ТК-17, контроллер задвижек и датчиков давления',
    description: 'Подающий и обратный трубопроводы, камера с задвижками, датчики давления, архив параметров теплосети.',
    serviceContext: 'Диспетчерская теплосети контролирует давление и температуру; ночные обходы только по аварийной заявке.',
  },
  {
    id: 'moscow-central-heat-point',
    title: 'ЦТП',
    facility: 'ЦТП квартала жилой застройки, Москва, район Аэропорт',
    region: 'Москва',
    connectionPoint: 'Шкаф телемеханики ЦТП-24, контроллер контуров отопления и ГВС',
    description: 'Теплообменники отопления и ГВС, подпитка, насосные группы, шлюз диспетчеризации и архив сменных параметров.',
    serviceContext: 'Рабочая смена обслуживает заявки жителей и УК; ночные вмешательства требуют подтверждения дежурного инженера.',
  },
]

export const demoIncidents: DemoIncident[] = [
  {
    id: 'ТАКТ-МКД-2026-0519-004',
    time: '19.05.2026 09:12:30 МСК',
    node: 'шкаф-штм-дом-01',
    invariant: 'штатный маршрут телеметрии',
    risk: 0.18,
    phase: 'рабочая',
    status: 'Ожидаемое поведение',
    operator: 'Иванов А.В.',
    summary: 'Плановый опрос ИТП прошёл через диспетчерскую УК и шкаф телемеханики без отклонений',
    serviceDesk: 'СД-МСК-ТЭ-5104',
    scenarioId: 'moscow-apartment-boiler',
    mode: 'NORMAL',
    phaseKey: 'WORK',
  },
  {
    id: 'ТАКТ-МКД-2026-0513-017',
    time: '13.05.2026 02:17:44 МСК',
    node: 'плк-итп-дом-01',
    invariant: 'обход переходного сервера',
    risk: 0.84,
    phase: 'ночь',
    status: 'Разбор',
    operator: 'Иванов А.В.',
    summary: 'АРМ инженера вышел к контроллеру ИТП жилого дома вне окна работ',
    scenarioId: 'moscow-apartment-boiler',
    mode: 'DEGRADED',
    phaseKey: 'NIGHT',
  },
  {
    id: 'ТАКТ-МКД-2026-0513-014',
    time: '13.05.2026 02:11:08 МСК',
    node: 'насос-гвс-дом-02',
    invariant: 'нестабильный интервал опроса',
    risk: 0.63,
    phase: 'ночь',
    status: 'Подтверждён',
    operator: 'Иванов А.В.',
    summary: 'Интервал опроса насосной группы ГВС стал нестабильным',
    scenarioId: 'moscow-apartment-boiler',
    mode: 'DEGRADED',
    phaseKey: 'NIGHT',
  },
  {
    id: 'ТАКТ-БОЛ-2026-0514-021',
    time: '14.05.2026 03:22:10 МСК',
    node: 'плк-котел-больница-01',
    invariant: 'доступ вне смены',
    risk: 0.91,
    phase: 'ночь',
    status: 'Разбор',
    operator: 'Петрова С.И.',
    summary: 'Вход в шкаф телемеханики резервной котельной без связанной заявки',
    scenarioId: 'moscow-hospital-boiler',
    mode: 'STORM',
    phaseKey: 'NIGHT',
  },
  {
    id: 'ТАКТ-БОЛ-2026-0514-018',
    time: '14.05.2026 01:48:35 МСК',
    node: 'архив-больница-01',
    invariant: 'падение свежести данных',
    risk: 0.72,
    phase: 'ночь',
    status: 'Подтверждён',
    operator: 'Петрова С.И.',
    summary: 'Архив резервной котельной отстаёт от телеметрии контроллера',
    scenarioId: 'moscow-hospital-boiler',
    mode: 'DEGRADED',
    phaseKey: 'NIGHT',
  },
  {
    id: 'ТАКТ-БОЛ-2026-0519-006',
    time: '19.05.2026 09:36:14 МСК',
    node: 'архив-больница-01',
    invariant: 'штатный просмотр архива',
    risk: 0.24,
    phase: 'рабочая',
    status: 'Ожидаемое поведение',
    operator: 'Петрова С.И.',
    summary: 'Дежурный инженер сверил архив резервной котельной больницы с текущей телеметрией',
    serviceDesk: 'СД-МСК-ТЭ-6208',
    scenarioId: 'moscow-hospital-boiler',
    mode: 'NORMAL',
    phaseKey: 'WORK',
  },
  {
    id: 'ТАКТ-ПРД-2026-0519-009',
    time: '19.05.2026 10:05:41 МСК',
    node: 'архив-смена-предприятие-01',
    invariant: 'архивирование сменных параметров',
    risk: 0.21,
    phase: 'рабочая',
    status: 'Закрыт',
    operator: 'Сидоров М.Н.',
    summary: 'Архив сменных параметров котельной предприятия совпал с журналом диспетчерской',
    serviceDesk: 'СД-МСК-ТЭ-9102',
    scenarioId: 'moscow-industrial-boiler',
    mode: 'NORMAL',
    phaseKey: 'WORK',
  },
  {
    id: 'ТАКТ-ТС-2026-0519-011',
    time: '19.05.2026 10:22:18 МСК',
    node: 'архив-теплосеть-тк17',
    invariant: 'штатная сверка давления',
    risk: 0.22,
    phase: 'рабочая',
    status: 'Ожидаемое поведение',
    operator: 'Кузнецова Е.П.',
    summary: 'Диспетчер сверил давление подачи и обратки по камере ТК-17 с архивом теплосети',
    serviceDesk: 'СД-МСК-ТЭ-7306',
    scenarioId: 'moscow-heat-network',
    mode: 'NORMAL',
    phaseKey: 'WORK',
  },
  {
    id: 'ТАКТ-ТС-2026-0515-033',
    time: '15.05.2026 02:41:57 МСК',
    node: 'датчик-давления-тк17',
    invariant: 'падение свежести данных',
    risk: 0.76,
    phase: 'ночь',
    status: 'Разбор',
    operator: 'Кузнецова Е.П.',
    summary: 'Датчик давления в тепловой камере ТК-17 отстал от архива и диспетчерского журнала',
    scenarioId: 'moscow-heat-network',
    mode: 'DEGRADED',
    phaseKey: 'NIGHT',
  },
  {
    id: 'ТАКТ-ЦТП-2026-0519-012',
    time: '19.05.2026 10:44:06 МСК',
    node: 'шкаф-цтп-24',
    invariant: 'штатный маршрут телеметрии',
    risk: 0.2,
    phase: 'рабочая',
    status: 'Ожидаемое поведение',
    operator: 'Орлова Н.К.',
    summary: 'Телеметрия ЦТП-24 поступила через штатный шкаф телемеханики и шлюз диспетчеризации',
    serviceDesk: 'СД-МСК-ТЭ-7420',
    scenarioId: 'moscow-central-heat-point',
    mode: 'NORMAL',
    phaseKey: 'WORK',
  },
  {
    id: 'ТАКТ-ЦТП-2026-0516-027',
    time: '16.05.2026 23:18:49 МСК',
    node: 'плк-гвс-цтп-24',
    invariant: 'нестабильный интервал опроса',
    risk: 0.68,
    phase: 'ночь',
    status: 'Подтверждён',
    operator: 'Орлова Н.К.',
    summary: 'Контур ГВС ЦТП-24 начал отвечать с нестабильным интервалом при пике нагрузки',
    scenarioId: 'moscow-central-heat-point',
    mode: 'STORM',
    phaseKey: 'NIGHT',
  },
  {
    id: 'ТАКТ-ПРД-2026-0512-088',
    time: '12.05.2026 22:44:03 МСК',
    node: 'шлюз-асутп-предприятие-01',
    invariant: 'новая связь',
    risk: 0.39,
    phase: 'обслуживание',
    status: 'Ожидаемое поведение',
    operator: 'Сидоров М.Н.',
    summary: 'Новая связь шлюза подтверждена заявкой на регламент сетевого насоса',
    serviceDesk: 'СД-МСК-ТЭ-8841',
    scenarioId: 'moscow-industrial-boiler',
    mode: 'NORMAL',
    phaseKey: 'MAINT',
  },
  {
    id: 'ТАКТ-ПРД-2026-0512-071',
    time: '12.05.2026 20:05:19 МСК',
    node: 'плк-насос-предприятие-03',
    invariant: 'регламентная связь',
    risk: 0.31,
    phase: 'обслуживание',
    status: 'Закрыт',
    operator: 'Сидоров М.Н.',
    summary: 'Проверка сетевого насоса прошла в окне обслуживания',
    serviceDesk: 'СД-МСК-ТЭ-8841',
    scenarioId: 'moscow-industrial-boiler',
    mode: 'AIR-GAP',
    phaseKey: 'MAINT',
  },
]

export const demoNodes: DemoNode[] = [
  { id: 'mkd-dispatch', label: 'Диспетчерская УК', kind: 'dispatch', x: 48, y: 16, state: 'normal', lastSeenDays: 0.1, scenarioId: 'moscow-apartment-boiler', modes: allModes, phases: allPhases },
  { id: 'mkd-cabinet', label: 'Шкаф ШТМ-1', kind: 'cabinet', x: 35, y: 38, state: 'warning', lastSeenDays: 0.1, scenarioId: 'moscow-apartment-boiler', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'mkd-arm', label: 'АРМ инженера УК', kind: 'engineering', x: 16, y: 67, state: 'warning', lastSeenDays: 0.2, scenarioId: 'moscow-apartment-boiler', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'mkd-plc', label: 'ПЛК ИТП дома', kind: 'plc', x: 62, y: 58, state: 'critical', lastSeenDays: 0.1, scenarioId: 'moscow-apartment-boiler', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'hospital-dispatch', label: 'Пост инженера больницы', kind: 'dispatch', x: 48, y: 15, state: 'normal', lastSeenDays: 0.1, scenarioId: 'moscow-hospital-boiler', modes: allModes, phases: allPhases },
  { id: 'hospital-cabinet', label: 'Шкаф ШТМ-Б', kind: 'cabinet', x: 34, y: 42, state: 'critical', lastSeenDays: 0.2, scenarioId: 'moscow-hospital-boiler', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'hospital-plc', label: 'ПЛК котла резерва', kind: 'plc', x: 63, y: 57, state: 'critical', lastSeenDays: 0.1, scenarioId: 'moscow-hospital-boiler', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'hospital-archive', label: 'Архив больницы', kind: 'archive', x: 79, y: 30, state: 'warning', lastSeenDays: 1.3, scenarioId: 'moscow-hospital-boiler', modes: ['DEGRADED'], phases: allPhases },
  { id: 'plant-dispatch', label: 'Диспетчерская предприятия', kind: 'dispatch', x: 50, y: 16, state: 'normal', lastSeenDays: 0.5, scenarioId: 'moscow-industrial-boiler', modes: allModes, phases: allPhases },
  { id: 'plant-cabinet', label: 'Шкаф ШТМ-П', kind: 'cabinet', x: 35, y: 42, state: 'normal', lastSeenDays: 2.3, scenarioId: 'moscow-industrial-boiler', modes: ['NORMAL', 'AIR-GAP'], phases: maintenanceOnly },
  { id: 'plant-pump-plc', label: 'ПЛК насоса №3', kind: 'plc', x: 61, y: 78, state: 'normal', lastSeenDays: 2.3, scenarioId: 'moscow-industrial-boiler', modes: ['NORMAL', 'AIR-GAP'], phases: maintenanceOnly },
  { id: 'plant-gateway', label: 'Шлюз АСУ ТП', kind: 'gateway', x: 82, y: 72, state: 'normal', lastSeenDays: 0.5, scenarioId: 'moscow-industrial-boiler', modes: allModes, phases: allPhases },
  { id: 'plant-archive', label: 'Архив смены', kind: 'archive', x: 78, y: 30, state: 'normal', lastSeenDays: 1.2, scenarioId: 'moscow-industrial-boiler', modes: ['NORMAL', 'DEGRADED'], phases: allPhases },
  { id: 'heatnet-dispatch', label: 'Диспетчерская теплосети', kind: 'dispatch', x: 48, y: 15, state: 'normal', lastSeenDays: 0.1, scenarioId: 'moscow-heat-network', modes: allModes, phases: allPhases },
  { id: 'heatnet-cabinet', label: 'Шкаф камеры ТК-17', kind: 'cabinet', x: 34, y: 42, state: 'normal', lastSeenDays: 0.1, scenarioId: 'moscow-heat-network', modes: allModes, phases: allPhases },
  { id: 'heatnet-plc', label: 'ПЛК задвижек ТК-17', kind: 'plc', x: 61, y: 55, state: 'warning', lastSeenDays: 0.2, scenarioId: 'moscow-heat-network', modes: allModes, phases: allPhases },
  { id: 'heatnet-sensor', label: 'Датчики давления', kind: 'sensor', x: 76, y: 72, state: 'warning', lastSeenDays: 0.4, scenarioId: 'moscow-heat-network', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'heatnet-gateway', label: 'Шлюз диспетчеризации', kind: 'gateway', x: 17, y: 68, state: 'normal', lastSeenDays: 0.3, scenarioId: 'moscow-heat-network', modes: allModes, phases: allPhases },
  { id: 'heatnet-archive', label: 'Архив теплосети', kind: 'archive', x: 80, y: 30, state: 'normal', lastSeenDays: 0.6, scenarioId: 'moscow-heat-network', modes: allModes, phases: allPhases },
  { id: 'ctp-dispatch', label: 'Диспетчерская ЦТП', kind: 'dispatch', x: 48, y: 15, state: 'normal', lastSeenDays: 0.1, scenarioId: 'moscow-central-heat-point', modes: allModes, phases: allPhases },
  { id: 'ctp-cabinet', label: 'Шкаф ЦТП-24', kind: 'cabinet', x: 34, y: 42, state: 'normal', lastSeenDays: 0.1, scenarioId: 'moscow-central-heat-point', modes: allModes, phases: allPhases },
  { id: 'ctp-plc-heating', label: 'ПЛК отопления', kind: 'plc', x: 62, y: 56, state: 'normal', lastSeenDays: 0.2, scenarioId: 'moscow-central-heat-point', modes: allModes, phases: allPhases },
  { id: 'ctp-plc-hws', label: 'ПЛК ГВС', kind: 'plc', x: 65, y: 78, state: 'warning', lastSeenDays: 0.3, scenarioId: 'moscow-central-heat-point', modes: allModes, phases: allPhases },
  { id: 'ctp-gateway', label: 'Шлюз диспетчеризации', kind: 'gateway', x: 82, y: 70, state: 'normal', lastSeenDays: 0.2, scenarioId: 'moscow-central-heat-point', modes: allModes, phases: allPhases },
  { id: 'ctp-archive', label: 'Архив ЦТП', kind: 'archive', x: 79, y: 30, state: 'normal', lastSeenDays: 0.8, scenarioId: 'moscow-central-heat-point', modes: allModes, phases: allPhases },
  { id: 'ctp-engineer', label: 'АРМ инженера УК', kind: 'engineering', x: 16, y: 67, state: 'warning', lastSeenDays: 0.2, scenarioId: 'moscow-central-heat-point', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
]

export const demoLinks: DemoLink[] = [
  { id: 'mkd-arm-cabinet', label: 'АРМ инженера → шкаф ШТМ-1', from: 'mkd-arm', to: 'mkd-cabinet', state: 'warning', lastSeenDays: 0.2, categories: ['engineering_bypass'], scenarioId: 'moscow-apartment-boiler', detail: 'Доступ инженерной станции ночью без связанной заявки УК', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'mkd-cabinet-plc', label: 'Шкаф ШТМ-1 → ПЛК ИТП дома', from: 'mkd-cabinet', to: 'mkd-plc', state: 'critical', lastSeenDays: 0.1, categories: ['engineering_bypass', 'plc'], scenarioId: 'moscow-apartment-boiler', detail: 'Подключение к контроллеру из шкафа телемеханики', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'mkd-dispatch-cabinet', label: 'Диспетчерская УК → шкаф ШТМ-1', from: 'mkd-dispatch', to: 'mkd-cabinet', state: 'normal', lastSeenDays: 0.1, categories: ['regular'], scenarioId: 'moscow-apartment-boiler', detail: 'Штатный маршрут телеметрии ИТП', modes: allModes, phases: allPhases },
  { id: 'hospital-dispatch-cabinet', label: 'Пост инженера → шкаф ШТМ-Б', from: 'hospital-dispatch', to: 'hospital-cabinet', state: 'warning', lastSeenDays: 0.2, categories: ['regular'], scenarioId: 'moscow-hospital-boiler', detail: 'Ночной доступ к резервной котельной больницы', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'hospital-dispatch-archive', label: 'Пост инженера → архив больницы', from: 'hospital-dispatch', to: 'hospital-archive', state: 'normal', lastSeenDays: 0.4, categories: ['regular'], scenarioId: 'moscow-hospital-boiler', detail: 'Штатный просмотр параметров резервной котельной', modes: allModes, phases: allPhases },
  { id: 'hospital-cabinet-plc', label: 'Шкаф ШТМ-Б → ПЛК котла резерва', from: 'hospital-cabinet', to: 'hospital-plc', state: 'critical', lastSeenDays: 0.1, categories: ['plc'], scenarioId: 'moscow-hospital-boiler', detail: 'Контроллер резервного котла в критичном объекте', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'hospital-plc-archive', label: 'ПЛК котла → архив больницы', from: 'hospital-plc', to: 'hospital-archive', state: 'warning', lastSeenDays: 1.3, categories: ['regular'], scenarioId: 'moscow-hospital-boiler', detail: 'Отставание архивных параметров резервной котельной', modes: ['DEGRADED'], phases: allPhases },
  { id: 'plant-cabinet-pump', label: 'Шкаф ШТМ-П → ПЛК насоса №3', from: 'plant-cabinet', to: 'plant-pump-plc', state: 'normal', lastSeenDays: 2.3, categories: ['plc'], scenarioId: 'moscow-industrial-boiler', detail: 'Регламентная проверка сетевого насоса', modes: ['NORMAL', 'AIR-GAP'], phases: maintenanceOnly },
  { id: 'plant-pump-gateway', label: 'ПЛК насоса №3 → шлюз АСУ ТП', from: 'plant-pump-plc', to: 'plant-gateway', state: 'normal', lastSeenDays: 2.3, categories: ['plc', 'gateway'], scenarioId: 'moscow-industrial-boiler', detail: 'Телеметрия насосной группы в контур АСУ ТП', modes: ['NORMAL', 'AIR-GAP'], phases: maintenanceOnly },
  { id: 'plant-dispatch-archive', label: 'Диспетчерская → архив смены', from: 'plant-dispatch', to: 'plant-archive', state: 'normal', lastSeenDays: 1.2, categories: ['regular'], scenarioId: 'moscow-industrial-boiler', detail: 'Архивирование сменных параметров котельной предприятия', modes: allModes, phases: allPhases },
  { id: 'heatnet-dispatch-cabinet', label: 'Диспетчерская теплосети → шкаф ТК-17', from: 'heatnet-dispatch', to: 'heatnet-cabinet', state: 'normal', lastSeenDays: 0.1, categories: ['regular'], scenarioId: 'moscow-heat-network', detail: 'Штатный канал телеметрии тепловой камеры ТК-17', modes: allModes, phases: allPhases },
  { id: 'heatnet-cabinet-plc', label: 'Шкаф ТК-17 → ПЛК задвижек', from: 'heatnet-cabinet', to: 'heatnet-plc', state: 'normal', lastSeenDays: 0.2, categories: ['plc'], scenarioId: 'moscow-heat-network', detail: 'Контроль положения задвижек и давления магистрали', modes: allModes, phases: allPhases },
  { id: 'heatnet-plc-sensor', label: 'ПЛК задвижек → датчики давления', from: 'heatnet-plc', to: 'heatnet-sensor', state: 'warning', lastSeenDays: 0.4, categories: ['plc'], scenarioId: 'moscow-heat-network', detail: 'Датчики давления отстают от цикла опроса камеры', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'heatnet-gateway-cabinet', label: 'Шлюз диспетчеризации → шкаф ТК-17', from: 'heatnet-gateway', to: 'heatnet-cabinet', state: 'warning', lastSeenDays: 0.3, categories: ['gateway'], scenarioId: 'moscow-heat-network', detail: 'Проверка маршрута через шлюз диспетчеризации теплосети', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'heatnet-dispatch-archive', label: 'Диспетчерская теплосети → архив', from: 'heatnet-dispatch', to: 'heatnet-archive', state: 'normal', lastSeenDays: 0.6, categories: ['regular'], scenarioId: 'moscow-heat-network', detail: 'Сверка архивных параметров подачи и обратки', modes: allModes, phases: allPhases },
  { id: 'ctp-dispatch-cabinet', label: 'Диспетчерская ЦТП → шкаф ЦТП-24', from: 'ctp-dispatch', to: 'ctp-cabinet', state: 'normal', lastSeenDays: 0.1, categories: ['regular'], scenarioId: 'moscow-central-heat-point', detail: 'Штатный маршрут телеметрии центрального теплового пункта', modes: allModes, phases: allPhases },
  { id: 'ctp-cabinet-heating', label: 'Шкаф ЦТП-24 → ПЛК отопления', from: 'ctp-cabinet', to: 'ctp-plc-heating', state: 'normal', lastSeenDays: 0.2, categories: ['plc'], scenarioId: 'moscow-central-heat-point', detail: 'Контроль контура отопления и подпитки', modes: allModes, phases: allPhases },
  { id: 'ctp-cabinet-hws', label: 'Шкаф ЦТП-24 → ПЛК ГВС', from: 'ctp-cabinet', to: 'ctp-plc-hws', state: 'warning', lastSeenDays: 0.3, categories: ['plc'], scenarioId: 'moscow-central-heat-point', detail: 'Контур ГВС показывает нестабильный интервал опроса при пике нагрузки', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
  { id: 'ctp-plc-gateway', label: 'ПЛК отопления → шлюз диспетчеризации', from: 'ctp-plc-heating', to: 'ctp-gateway', state: 'normal', lastSeenDays: 0.2, categories: ['gateway'], scenarioId: 'moscow-central-heat-point', detail: 'Передача параметров ЦТП в диспетчерский контур', modes: allModes, phases: allPhases },
  { id: 'ctp-gateway-archive', label: 'Шлюз диспетчеризации → архив ЦТП', from: 'ctp-gateway', to: 'ctp-archive', state: 'normal', lastSeenDays: 0.8, categories: ['regular'], scenarioId: 'moscow-central-heat-point', detail: 'Архивирование температур и расхода по контурам ЦТП', modes: allModes, phases: allPhases },
  { id: 'ctp-engineer-cabinet', label: 'АРМ инженера УК → шкаф ЦТП-24', from: 'ctp-engineer', to: 'ctp-cabinet', state: 'warning', lastSeenDays: 0.2, categories: ['engineering_bypass'], scenarioId: 'moscow-central-heat-point', detail: 'Ночной доступ инженерной станции к шкафу ЦТП требует подтверждения наряда', modes: ['DEGRADED', 'STORM'], phases: nightOnly },
]

export const demoInvariantGroups = [
  ['Сетевые связи', 'Новая связь', 'Неожиданный маршрут', 'Обход переходного сервера', 'Дрейф сегмента'],
  ['Ритм опроса', 'Нестабильный интервал опроса', 'Разрыв обмена с ПЛК', 'Нарушение цикла опроса', 'Прогноз бифуркации опроса'],
  ['Смена и доступ', 'Доступ вне смены', 'Несоответствие роли КИПиА', 'Нет заявки службы сопровождения', 'Задержка решения оператором'],
  ['Качество данных', 'Падение свежести данных', 'Частичная наблюдаемость', 'Молчание источника', 'Смещение часов'],
  ['Тепловой процесс', 'Расхождение подачи и обратки', 'Скачок давления сетевого насоса', 'Эхо исполнительного механизма', 'Плато температуры', 'Инерция изменения температуры'],
  ['Риск и аудит', 'Ускорение риска', 'Экспертное расхождение', 'Сдвиг базовой линии', 'Готовность выгрузки', 'Изоляция контура подтверждена'],
] as const

export const demoAuditEvents = [
  '02:18:02 Иванов А.В. открыл ТАКТ-МКД-2026-0513-017',
  '02:18:13 Подготовлен сдвиг базовой линии ИТП, ожидает решения оператора',
  '02:18:27 Доказательный пакет доступен локально',
  '02:19:04 Иванов А.В. добавил комментарий к инциденту',
]
