#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import re
from pathlib import Path


def _extract_value(text: str, key: str) -> str:
    m = re.search(rf"-\s+{re.escape(key)}:\s+`([^`]+)`", text)
    return m.group(1).strip() if m else ""


def _detect_forensic_mode() -> str:
    crypto_mode = os.getenv("TAKT_FORENSIC_CRYPTO_MODE", "").strip().lower()
    sign_url = os.getenv("TAKT_FORENSIC_SIGN_URL", "").strip()
    verify_url = os.getenv("TAKT_FORENSIC_VERIFY_URL", "").strip()
    hmac_secret = os.getenv("TAKT_FORENSIC_HMAC_SECRET", "").strip()
    if crypto_mode == "gost_strict":
        if sign_url and verify_url:
            return "gost_strict (TAKT_FORENSIC_SIGN_URL + TAKT_FORENSIC_VERIFY_URL)"
        return "gost_strict (misconfigured: missing sign/verify env)"
    if sign_url and verify_url:
        return "external (TAKT_FORENSIC_SIGN_URL + TAKT_FORENSIC_VERIFY_URL)"
    if hmac_secret:
        return "HMAC (TAKT_FORENSIC_HMAC_SECRET)"
    return "unknown (env not set locally)"


def _normalize_path_for_card(value: str, prod_ready_path: Path) -> str:
    raw = (value or "").strip()
    if not raw:
        return ""
    candidate = Path(raw)
    if not candidate.is_absolute():
        return raw.replace("\\", "/")
    root = prod_ready_path.resolve().parents[2]
    try:
        rel = candidate.resolve().relative_to(root)
        return rel.as_posix()
    except Exception:
        return raw.replace("\\", "/")


def run(evidence_path: Path, prod_ready_path: Path, *, forensic_mode: str = "") -> int:
    evidence = evidence_path.read_text(encoding="utf-8")
    prod = prod_ready_path.read_text(encoding="utf-8")

    backup_path = _extract_value(evidence, "backup_path")
    migrate_done = _extract_value(evidence, "migrate_done")
    smoke_case_id = _extract_value(evidence, "smoke_case_id")
    gossopka_official_ok = _extract_value(evidence, "gossopka_official_ok")
    forensic_signing_unavailable = _extract_value(evidence, "forensic_signing_unavailable")
    forensic_ok = _extract_value(evidence, "forensic_verify_ok")
    audit_engagement_ok = _extract_value(evidence, "audit_engagement_api_ok")
    forensic_mode_value = (forensic_mode or "").strip() or _detect_forensic_mode()
    backup_path = _normalize_path_for_card(backup_path, prod_ready_path)

    smoke_summary = (
        "case_id="
        f"{smoke_case_id}; "
        f"gossopka_official_ok={gossopka_official_ok}; "
        f"forensic_signing_unavailable={forensic_signing_unavailable}; "
        f"forensic_verify_ok={forensic_ok}; "
        f"audit_engagement_api_ok={audit_engagement_ok}"
    ).strip("; ")

    updated_lines: list[str] = []
    for line in prod.splitlines():
        if line.startswith("## 2)"):
            updated_lines.append("## 2) Manual input required (4 поля)")
            continue
        if line.startswith("| 5. Backup"):
            updated_lines.append(f"| 5. Backup БД выполнен (путь к backup) | `{backup_path or 'N/A'}` |")
            continue
        if line.startswith("| 6. `db_migrate.py`"):
            updated_lines.append(f"| 6. `db_migrate.py` выполнен (версия схемы/вывод) | `{migrate_done or 'unknown'}` |")
            continue
        if line.startswith("| 8. Smoke-check"):
            updated_lines.append(f"| 8. Smoke-check после выкладки (ссылка/лог) | `{smoke_summary or 'N/A'}` |")
            continue
        if line.startswith("| 7."):
            updated_lines.append(f"| 7. Режим forensic подписи в prod (`mvp` или `gost_strict` + env) | `{forensic_mode_value}` |")
            continue
        updated_lines.append(line)
    prod = "\n".join(updated_lines) + "\n"

    prod_ready_path.write_text(prod, encoding="utf-8")
    print(f"prod_ready_updated={prod_ready_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Fill prod-ready card fields from operational tails evidence markdown.")
    parser.add_argument(
        "--evidence",
        default="docs/releases/operational_tails_evidence.md",
        help="Path to evidence markdown generated by close_operational_tails.py",
    )
    parser.add_argument(
        "--prod-ready",
        default="docs/releases/2026-05-07_v0.6.23_prod_ready.md",
        help="Path to prod-ready markdown to update.",
    )
    parser.add_argument(
        "--forensic-mode",
        default="",
        help="Optional explicit value for field 7. If empty, inferred from local TAKT_FORENSIC_* environment variables.",
    )
    args = parser.parse_args()
    return run(
        Path(args.evidence).expanduser().resolve(),
        Path(args.prod_ready).expanduser().resolve(),
        forensic_mode=args.forensic_mode,
    )


if __name__ == "__main__":
    raise SystemExit(main())
